### ISSUE TITLE
Already configured networks dont show bssid

### ISSUE THREAD

**Issue by bonanza123** [theyosh/WiFiKilL3r#3]
When I click on add trusted network, only the bssid of those networks is listed who haven't yet been configured.

**Comment by fuchsmich** [comment]
...got the same issue.

**Comment by theyosh** [comment]
Ok, sorry for not answering earlier. But I am afraid that this is an issue inside Jolla OS. I use standard API calls to get Wifi networks from Jolla OS. Therefore I do not control if the bssid is shown.
But I did found out, that it looks like this happens when a known network (you home) has changed the Wifi accesspoint hardware. In other words, Jolla seems to know more then one bssid with the network name, and will not show it correctly.

I had this lately due to hardware change. And did see the bssid is missing. The only way I could solve this is by deleting the wifi network from the Wlan known networks. And then reconnect again.

So it looks like when the Wifi name has more then one bssid address (multiple stations) it can be a problem to get it to work. 

Try removing you Wifi network from the WLAN setttings, and add again. Then try my app to see if the bssid is shown again.

**Comment by bonanza123** [comment]
thanks for your feedback. Maybe a stupid question: Would it be possible to interface connman directly, thus, avoiding SFOS API?

**Comment by theyosh** [comment]
Could be, but I do not have much knowledge of the QT/QML code and mobile connman etc. So I made this as a kind of hack. And the code for network scanning is just copied from an example that the IDE provided. So I did not bother to change that.

Maybe in the future, but for me it is working enough so I do not have much priority to rewrite it right now.
